version: "3"

services:
    php:
        container_name: ttrdata-php
        build:
            context: ./docker-compose/php
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./:/var/www
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app

    nginx:
        container_name: ttrdata-nginx
        build:
            context: ./docker-compose/nginx
            dockerfile: Dockerfile
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    setup-data:
        driver: local
